#给application配置文件注入具体数据
# 【自定义业务配置根节点】所有项目专属的配置均在 sky 节点下，便于统一管理和注入
sky:
  # 【数据库连接配置】（为 Spring 数据源 druid 提供具体参数，覆盖主配置中的占位符）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 15724835
  # 【阿里云 OSS 配置】（用于存储项目中的图片资源，如菜品图片、用户头像、套餐封面等）
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  # 【Redis 缓存配置】（为 Spring Redis 提供具体参数，用于缓存高频访问数据）
  redis:
    host: localhost
    port: 6379
    password: 15724835
    database: 10
  # 【微信支付/登录配置】（适配微信小程序/公众号的登录、支付、退款功能，推测为外卖项目的核心支付渠道）
  wechat:
    appid:
    secret:
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:

